<?php
return [
    'button.add' => 'Add',
    'button.done' => 'Done',
    'button.download' => 'Download',
    'button.edit' => 'Edit',
    'button.more' => 'More',
    'button.remove' => 'Remove',
    'button.report' => 'Report',
    'button.save' => 'Save',
    'button.upload' => 'Upload',
    'confirm.continue' => 'Are you sure want to continue?',
    'image.email_site_name' => '@@en/email/ely-by.png@@',
    'image.email_site_name_footer' => '@@en/email/ely-by-footer.png@@',
    'text.cube' => 'Cube it',
    'text.uncube' => 'Uncube',
    'title.append' => 'Skins system Ely.by',
    'title.site_description' => 'Alternative Minecraft services',
    'title.site_name' => 'Ely.by',
    'title.site_name_full' => 'Skins gallery and skins system for Mineraft Ely.by',
];
