<?php
return [
    'confirm.remove' => 'Are you sure you want to delete this post?',
    'menu.get_link' => 'Get link',
    'menu.pin_post' => 'Pin post',
    'menu.unpin_post' => 'Unpin post',
    'text.collapse_comments' => 'Collapse comments',
    'text.error_can_not_repost_own_post' => 'You can not repost your own post.',
    'text.error_only_author_can_edit' => 'Only post author can edit it.',
    'text.error_only_friend_can_post' => 'To write on this wall you need to add user in friend list.',
    'text.error_only_owner_can_post' => 'Only wall owner can write on it.',
    'text.error_post_delete' => 'You can not delete this post.',
    'text.error_post_not_exists' => 'The requested post does not exists.',
    'text.get_link' => 'Select and copy this link, to share it with your friends.',
    'text.load_old_comments' => 'Load old comments',
    'text.post_is_pinned' => 'This post is pinned',
    'text.success_post_attach' => 'Post successfully pinned. Now it will be always shown on top of all post.',
    'text.success_post_create' => 'New post was successfully added to your wall.',
    'text.success_post_delete' => 'Post was successfully removed.',
    'text.success_post_detach' => 'Post was successfully unpinned.',
    'text.x_comments' => '{commentsCount, plural,
        one   {# comment}
        other {# comments}
    }',
    'title' => 'Post #{postNumber}',
    'title.add_new_post' => 'Add new post',
    'title.get_link' => 'Get direct link',
    'tooltip.repost' => 'Repost',
    'tooltip.undo_repost' => 'Undo repost',
];
