<?php
return [
    'button.change' => 'Change',
    'button.save_settings' => 'Save settings',
    'password_example' => 'yes, your password',
    'text.account_settings' => 'Account settings:',
    'text.account_settings_description' => 'Minecraft nickname, assigned E-mail and account password is controlled via our external service "Accounts Ely.by". Here you can view their current values, but to change it you have to visit external site.',
    'text.category_account' => 'Account',
    'text.category_general' => 'General',
    'text.category_notifications' => 'Notifications',
    'text.category_privacy' => 'Privacy',
    'text.email' => 'E-mail:',
    'text.error_static_url_already_exists' => 'This url is already bond to another account.',
    'text.error_unexist_locale' => 'The chosen language is not supported.',
    'text.gender' => 'You gender:',
    'text.gender_female' => 'Female',
    'text.gender_male' => 'Male',
    'text.gender_not_set' => 'Not specified',
    'text.minecraft_username' => 'Minecraft username:',
    'text.nickname' => 'Nickname:',
    'text.nickname_desc' => 'Hint: you just changed your site\'s nickname, if you want to <b>change Minecraft nickname</b> you should go to <a href="#account" class="no-ajax">Account tab</a>.',
    'text.notifications_desc_chat_message' => 'An unread messages is in chat',
    'text.notifications_desc_comments' => 'For your content (post, skin, etc.), or content, track by you added a new comment',
    'text.notifications_desc_friends_invite' => 'User offers friendship',
    'text.notifications_desc_friends_result' => 'The user whom you added to the friends accepted or rejected your invitation',
    'text.notifications_desc_posts' => 'Your friend or the user to whom you\'ve subscribed, added a new post on the wall',
    'text.notifications_on_email' => 'On E-mail',
    'text.notifications_on_site' => 'On site',
    'text.notifications_settings' => 'Notification settings:',
    'text.password' => 'Password:',
    'text.privacy_can_invite_to_friends' => '{selected_index, select,
        0     {can invite me as a friend.}
        1     {can invite a friend.}
        other {accept invitations to friends.}
    }',
    'text.privacy_can_write_comments_to_posts' => 'can comment on my posts.',
    'text.privacy_can_write_on_wall' => 'can write on my wall.',
    'text.privacy_can_write_to_chat' => 'can write in the chat.',
    'text.privacy_settings' => 'Privacy settings:',
    'text.select_all' => 'Anyone',
    'text.select_auto' => 'Automatically',
    'text.select_only_friends' => 'Only friends',
    'text.select_only_me' => 'Only me',
    'text.settings_title' => 'Settings:',
    'text.site_language' => 'Site language:',
    'text.static_url' => 'Static Url:',
    'text.static_url_desc' => '<b>Static url can not be changed and can not be removed.</b> Your profile will also be available at the usual link (<a href="{userDefaultUrl}">{userDefaultUrl}</a>). Although the value is in lower case, the profile will be available even if you write <a href="/ErickSkrauch">http://ely.by/ErickSkrauch</a> or <a href="/ErIcKsKrAuCh">http://ely.by/ErIcKsKrAuCh</a>.',
    'text.static_url_wrong_chars' => 'Static url contains forbidden characters. It should contain from 3 to 30 alphanumeric characters.',
    'text.success_settings_edit' => 'Settings was successfully saved.',
    'title' => 'Settings',
];
