<?php
return [
    'button.accept' => 'Aceitar',
    'button.chat' => 'Chat',
    'button.decline_request' => 'Pedido negado',
    'confirm.remove' => 'Tem certeza de que deseja remover este usuário de seus amigos?',
    'text.error_accept_friendship' => 'Você já aceitou a amizade com este usuário.',
    'text.error_already_friends' => 'Você já é amigo deste usuário.',
    'text.error_friendship_access' => 'Este usuário não aceita pedidos de amizade. Você pode se inscrever nele, para ver suas novas postagens.',
    'text.error_not_friends' => 'Vocês não são amigos.',
    'text.friend_list_is_loading' => 'Lista de amigos carregando...',
    'text.success_accept_friendship' => 'Você aceitou a amizade com este usuário.',
    'text.success_cancel_friendship' => 'Você já não é amigo deste usuário.',
    'text.success_request_friendship' => 'Seu pedido de amizade foi enviado com sucesso para o usuário atual.',
    'text.you_have_no_friends_yet' => 'Você não tem amigos ainda. Tente pesquisar por seus apelidos.',
    'title' => '{username} amigos',
    'title.filter_all' => 'Tudo',
    'title.filter_offline' => 'Offline',
    'title.filter_online' => 'Online',
    'title.filter_pending' => 'Pendente',
    'title.friends_list' => 'Lista de amigos',
];
