<?php
return [
    'button.change' => 'Mudar',
    'button.save_settings' => 'Salvar configurações',
    'password_example' => 'Sim, a sua senha',
    'text.account_settings' => 'Configurações da conta:',
    'text.account_settings_description' => 'O nome de usuário no Minecraft, o e-mail escolhido e a senha é controlado pelo nosso serviço de "Contas Ely.by". Aqui você pode ver seus valores atuais, mas se quiser muda-los, terá que usar o site externo.',
    'text.category_account' => 'Conta',
    'text.category_general' => 'Geral',
    'text.category_notifications' => 'Notificações',
    'text.category_privacy' => 'Privacidade',
    'text.email' => 'E-mail:',
    'text.error_static_url_already_exists' => 'Esta URL estática já está ligado a outra conta.',
    'text.error_unexist_locale' => 'O idioma escolhido não é suportado.',
    'text.gender' => 'Seu genêro:',
    'text.gender_female' => 'Feminino',
    'text.gender_male' => 'Masculino',
    'text.gender_not_set' => 'Não especificado',
    'text.minecraft_username' => 'Nome de usuário no minecraft:',
    'text.nickname' => 'Apelido:',
    'text.notifications_desc_chat_message' => 'Mensagens não lidas no chat',
    'text.notifications_desc_comments' => 'Para o seu conteúdo (postagem, skin, etc.), ou outro conteúdo, faça um novo comentário',
    'text.notifications_desc_friends_invite' => 'Usuário oferece amizade',
    'text.notifications_desc_friends_result' => 'O usuário que você adicionou aos amigos aceitou ou rejeitou seu convite',
    'text.notifications_desc_posts' => 'Seu amigo ou o usuário a quem você se inscreveu, adicionou uma nova mensagem na parede',
    'text.notifications_on_email' => 'Por E-mail',
    'text.notifications_on_site' => 'Por site',
    'text.notifications_settings' => 'Configurações de notificação:',
    'text.password' => 'Senha:',
    'text.privacy_can_invite_to_friends' => '{selected_index, select,
        0     {pode convidar-me como um amigo.}
        1     {pode convidar um amigo.}
        other {aceitar convites para os amigos.}
    }',
    'text.privacy_can_write_comments_to_posts' => 'Pode comentar sobre as minhas postagens.',
    'text.privacy_can_write_on_wall' => 'Pode escrever no meu mural.',
    'text.privacy_can_write_to_chat' => 'Pode escrever no chat.',
    'text.privacy_settings' => 'Configurações de privacidade:',
    'text.select_all' => 'Todo mundo',
    'text.select_auto' => 'Automaticamente',
    'text.select_only_friends' => 'Somente amigos',
    'text.select_only_me' => 'Somente eu',
    'text.settings_title' => 'Configurações:',
    'text.site_language' => 'Idioma do site:',
    'text.static_url' => 'URL estática:',
    'text.static_url_desc' => '<b>A URL estática não pode ser alterada e não pode ser removida.</b> O seu perfil também estará disponível no link usual (<a href="{userDefaultUrl}">{userDefaultUrl}</a>). Embora o valor é em letras minúsculas, o perfil estará disponível mesmo se você escrever <a href="/ErickSkrauch">http://ely.by/ErickSkrauch</a> ou <a href="/ErIcKsKrAuCh">http://ely.by/ErIcKsKrAuCh</a>.',
    'text.static_url_wrong_chars' => 'A URL estática contém carácteres proibidos. Ela deve conter de 3 a 30 caracteres alfanuméricos.',
    'text.success_settings_edit' => 'Configurações salvas com sucesso',
    'title' => 'Configurações',
];
