<?php
return [
    'button.accept' => 'Принять',
    'button.chat' => 'Написать',
    'button.decline_request' => 'Отменить заявку',
    'confirm.remove' => 'Вы действительно хотите удалить этого пользователя из списка своих друзей?',
    'text.error_accept_friendship' => 'Вы уже подтвердили свою дружбу с этим пользователем.',
    'text.error_already_friends' => 'Вы уже дружите с этим пользователем.',
    'text.error_friendship_access' => 'Этот пользователь запретил приглашать себя в друзья. Вы можете подписаться на него, чтобы следить за его постами.',
    'text.error_not_friends' => 'Вы не являетесь друзьями.',
    'text.friend_list_is_loading' => 'Идет загрузка списка друзей...',
    'text.success_accept_friendship' => 'Вы успешно подтвердили свою дружбу с указанным пользователем.',
    'text.success_cancel_friendship' => 'Вы больше не являетесь друзьями с этим пользователем.',
    'text.success_request_friendship' => 'Пользователю успешно отправлено предложение стать друзьями.',
    'text.you_have_no_friends_yet' => 'У вас пока нет друзей. Попробуйте воспользоваться поиском по никам своих друзей.',
    'title' => 'Друзья {username}',
    'title.filter_all' => 'Все',
    'title.filter_offline' => 'Не в сети',
    'title.filter_online' => 'В сети',
    'title.filter_pending' => 'В ожидании',
    'title.friends_list' => 'Список друзей',
];
