<?php
return [
    'button.change' => 'Изменить',
    'button.save_settings' => 'Сохранить настройки',
    'password_example' => 'да, это твой пароль',
    'text.account_settings' => 'Настройки аккаунта:',
    'text.account_settings_description' => 'Игровой ник, привязанный E-mail адрес и пароль от аккаунта управляется нашим внешним сервисом "Аккаунты Ely.by". Здесь можно ознакомиться с их текущими значениями, но для изменения необходимо перейти на внешний сайт.',
    'text.category_account' => 'Аккаунт',
    'text.category_general' => 'Основные',
    'text.category_notifications' => 'Уведомления',
    'text.category_privacy' => 'Приватность',
    'text.email' => 'E-mail:',
    'text.error_static_url_already_exists' => 'Данный url уже привязан к другому аккаунту.',
    'text.error_unexist_locale' => 'Выбранный язык не поддерживается.',
    'text.gender' => 'Ваш пол:',
    'text.gender_female' => 'Женский',
    'text.gender_male' => 'Мужской',
    'text.gender_not_set' => 'Не задан',
    'text.minecraft_username' => 'Ник в Minecraft:',
    'text.nickname' => 'Никнейм:',
    'text.nickname_desc' => 'Обратите внимание: здесь вы меняете ник на сайте. <b>Сменить ник в Minecraft</b> можно на <a href="#account" class="no-ajax">вкладке Аккаунт</a>.',
    'text.notifications_desc_chat_message' => 'Непрочитанное сообщение в диалоге',
    'text.notifications_desc_comments' => 'К вашему материалу (пост, скин и т.д.) или материалу, отслеживаемому вами, добавили новый комментарий',
    'text.notifications_desc_friends_invite' => 'Пользователь предлагает дружбу',
    'text.notifications_desc_friends_result' => 'Пользователь, которого вы добавили в друзья принял или отклонил ваше приглашение',
    'text.notifications_desc_posts' => 'Ваш друг или пользователь, на которого вы подписаны, добавил новый пост на стену',
    'text.notifications_on_email' => 'На почту',
    'text.notifications_on_site' => 'На сайте',
    'text.notifications_settings' => 'Настройки уведомлений:',
    'text.password' => 'Пароль:',
    'text.privacy_can_invite_to_friends' => '{selected_index, select,
        0     {могут приглашать меня в друзья.}
        1     {могу приглашать в друзья.}
        other {принимать приглашения в друзья.}
    }',
    'text.privacy_can_write_comments_to_posts' => 'могут писать комментарии к моим постам.',
    'text.privacy_can_write_on_wall' => '{selected_index, select, 2{могу} other{могут}} писать на мою стену.',
    'text.privacy_can_write_to_chat' => 'могут писать мне в чат.',
    'text.privacy_settings' => 'Настройки приватности:',
    'text.select_all' => 'Все',
    'text.select_auto' => 'Автоматически',
    'text.select_only_friends' => 'Только друзья',
    'text.select_only_me' => 'Только я',
    'text.settings_title' => 'Настройки:',
    'text.site_language' => 'Язык сайта:',
    'text.static_url' => 'Статический Url:',
    'text.static_url_desc' => '<b>Статический url нельзя изменить и нельзя удалить.</b> Ваш профиль так же будет доступен по обычной ссылке (<a href="{userDefaultUrl}">{userDefaultUrl}</a>). Хотя значение приводится к нижнему регистру, профиль будет доступен даже если написать <a href="/ErickSkrauch">http://ely.by/ErickSkrauch</a> или <a href="/ErIcKsKrAuCh">http://ely.by/ErIcKsKrAuCh</a>.',
    'text.static_url_wrong_chars' => 'Статический url содержит запрещённые символы. Он должен быть от 3 до 30 символов в длинну и не содержать специфических символов.',
    'text.success_settings_edit' => 'Настройки успешно применены.',
    'title' => 'Настройки',
];
