<?php
return [
    'button.add' => 'Дабавіць',
    'button.done' => 'Гатова',
    'button.download' => 'Спампаваць',
    'button.edit' => 'Змяніць',
    'button.more' => 'Падрабязней',
    'button.remove' => 'Выдаліць',
    'button.report' => 'Паскардзіцца',
    'button.save' => 'Захаваць',
    'button.upload' => 'Загрузіць',
    'confirm.continue' => 'Вы ўпэўнены, што хочаце прадоўжыць?',
    'image.email_site_name' => '@@ru/email/ely-by.png@@',
    'image.email_site_name_footer' => '@@ru/email/ely-by-footer.png@@',
    'text.cube' => 'Кубнуць',
    'text.uncube' => 'Зняць куб',
    'title.append' => 'Сістэма скіноў Ely.by',
    'title.site_description' => 'Альтэрнатыўныя сэрвісы Minecraft',
    'title.site_name' => 'Ely.by',
    'title.site_name_full' => 'Каталог і сістэма скіноў для Mineraft Ely.by',
];
